#nombre que va a tener nuestro microservicio
spring.application.name=compra-service
#puerto en el que va a correr nuestro microservicio
server.port=4444

#ya que vamos a utilizar un almacenamiento h2 en memoria, quiere decir que cuando nuestra aplicación se levante, se va a crear una base de datos en memoria, y en cuanto detenagmos la aplicación, la base de datos se va a destruir automáticamente

#configuración de la base de datos (donde y como se va a llamar la base de datos, y el usuario y contraseña de acceso)
spring.datasource.url=jdbc:h2:mem:db_compra
spring.datasource.username=root
spring.datasource.password=1234

#driver que vamos a utilizar para conección a la base de datos
spring.datasource.driver-class-name=org.h2.Driver
#dialecto que vamos a utilizar para la comunicación con la base de datos
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#indicamos que cada que generemos una consulta a la base de datos, se muestre en consola
spring.jpa.show-sql=true
#configuración para la comunicación con otros microservicios (de momento inhabilitada)
eureka.client.enable=true


# declaracion que defini dentro del security config
service.security.secure-key-username=omar2026username 
service.security.secure-key-password=omar2026password
